server {
  listen 5000;
  server_name conductor;
  root /usr/share/nginx/html;
  location / { try_files $uri /index.html; }
  location /api { proxy_pass http://conductor-server:8080/api; }
  location /actuator { proxy_pass http://conductor-server:8080/actuator; }
}
