conductor.db.type=redis_standalone
conductor.queue.type=redis_standalone
conductor.redis.hosts=conductor-redis:6379:us-east-1c
conductor.redis-lock.serverAddress=redis://conductor-redis:6379
conductor.redis.taskDefCacheRefreshInterval=1
conductor.redis.workflowNamespacePrefix=conductor
conductor.redis.queueNamespacePrefix=conductor_queues
conductor.workflow-execution-lock.type=redis
conductor.app.workflowExecutionLockEnabled=true
conductor.app.lockTimeToTry=500
conductor.app.systemTaskWorkerThreadCount=20
conductor.app.systemTaskMaxPollCount=20
conductor.indexing.enabled=true
conductor.indexing.type=elasticsearch
conductor.elasticsearch.url=http://conductor-elasticsearch:9200
conductor.elasticsearch.indexName=conductor
conductor.elasticsearch.version=7
conductor.elasticsearch.clusterHealthColor=yellow
conductor.metrics-prometheus.enabled=true
management.endpoints.web.exposure.include=health,prometheus
management.health.redis.enabled=true
conductor.redis.ssl=false
conductor.app.ownerEmailMandatory=false
loadSample=false
conductor.file-storage.enabled=true
conductor.file-storage.type=conductor
