import assert from 'node:assert/strict';
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { migrate } from '../src/mock/migrate';
import { seed } from '../src/mock/seed';
import { activeCells, executorCells, flowCells, lastUserInput, parseUsage, taskElapsedSeconds, waitingSeconds, supported } from '../src/mock/model';
import { addCellInstruction, successorCellIds, addInstruction, advance, answerQuestions, createTask, insertCell, interruptTask, recordTask, restartTask, retryCell, sceneState } from '../src/mock/actions';
import { longReport } from '../src/mock/content';

const s = seed();
assert(s.tasks.length >= 8);
assert.equal(s.executors.length, 6);
assert.equal(executorCells(s, 'codex-personal').length, 3);
assert.equal(new Set(executorCells(s, 'codex-personal').map(x => x.task.id)).size, 2);
assert.equal(flowCells(s.tasks.find(t => t.id === 'large')!.flow).length, 30);
assert.equal(s.tasks.find(t => t.id === 'large')!.flow.rounds.length, 8);
assert(longReport.length >= 3000);
for (const t of s.tasks) { const run = t.flow;
  const cells = flowCells(run), ids = cells.map(c => c.id); assert.equal(new Set(ids).size, ids.length);
  for (const report of run.reports) { assert(cells.some(c => c.id === report.id && c.kind === 'report')); if (report.questions.length) assert(run.rounds.some(r => r.report?.id === report.id && r.joined && r.branches.some(b => b.waiting && b.cells.find(c => c.id === b.waiting?.observerId)?.kind === 'observe'))); }
  for (const c of cells) if (c.kind !== 'owner') assert(supported(s.executors.find(e => e.id === c.executor)!, c.type), `${c.id} has unsupported executor`);
}
const a = s.tasks.find(t => t.id === 'api')!;
interruptTask(a, '読み取りだけに切り替える'); assert.equal(activeCells(a).length, 0); assert(a.flow.rounds[0].branches.every(b => b.cells.some(c => c.decision === '分岐 A：オブザーバー')));
addInstruction(a, '追加の条件'); assert(a.flow.rounds.at(-1)!.owners.some(c => c.input === '追加の条件'));
const after = insertCell(a, 'api-r1-judge', 'after', 'verify.lint', '静的検査', s.executors); assert.equal(flowCells(a.flow).find(c => c.id === after)?.after, 'api-r1-judge');
const parallel = insertCell(a, 'api-implement', 'parallel', 'verify.test', '並列検査', s.executors); assert.equal(flowCells(a.flow).find(c => c.id === parallel)?.after, 'api-r1-judge');
const previousIds = flowCells(a.flow).map(c => c.id); restartTask(a, '新しい条件'); assert(previousIds.every(id => flowCells(a.flow).some(c => c.id === id))); assert(!('runs' in a)); assert.equal(activeCells(a).length, 1);
const q = s.tasks.find(t => t.id === 'questions')!, report = q.flow.reports[0];
const beforeAnswers = structuredClone(q);
assert.equal(answerQuestions(q, report.id, { approve: '承認する' }), false); assert.deepEqual(q, beforeAnswers);
assert.equal(answerQuestions(q, report.id, { approve: '   ', destination: 'それ以外の保存先', conditions: '条件' }), false); assert.deepEqual(q, beforeAnswers);
assert.equal(answerQuestions(q, report.id, { approve: '読み取り対象を先に確認する', destination: '共有の候補として保留', conditions: '個人情報を含む記録は除く' }), true);
assert.equal(q.state, '進行中'); assert.equal(q.flow.rounds.at(-1)!.owners.filter(c => c.type === '返答').length, 1);
const afterAnswers = structuredClone(q); assert.equal(answerQuestions(q, report.id, { approve: '回答', destination: '回答', conditions: '回答' }), false); assert.deepEqual(q, afterAnswers);
assert.equal(lastUserInput(q, report.id), beforeAnswers.initial);
const multiple = sceneState('複数の報告').tasks.find(t => t.id === 'questions')!;
assert.equal(multiple.flow.reports.length, 3); assert.equal(new Set(multiple.flow.reports.map(r => r.id)).size, 3);
assert.equal(new Set(multiple.flow.reports.map(r => lastUserInput(multiple, r.id))).size, 3);
assert(multiple.flow.reports.every(r => flowCells(multiple.flow).some(c => c.id === r.id)));
assert.equal(answerQuestions(multiple, multiple.flow.reports[0].id, {}), false);
const retry = s.tasks.find(t => t.id === 'retry')!, failed = flowCells(retry.flow).find(c => c.state === '失敗した')!;
const copyId = retryCell(retry, failed, 'claude-personal'); assert(flowCells(retry.flow).some(c => c.id === copyId && c.input === failed.input));
const simulation = seed(); simulation.tasks = [createTask('模擬的に進める', '')];
const steps: string[] = []; for (let i = 0; i < 24 && simulation.tasks[0].state === '進行中'; i++) steps.push(advance(simulation));
assert.equal(simulation.tasks[0].state, '入力待ち'); assert(steps.some(s => s.includes('オブザーバー'))); assert(steps.some(s => s.includes('合流'))); assert(simulation.tasks[0].flow.reports.length);
recordTask(simulation.tasks[0], '完了'); advance(simulation); assert.equal(simulation.tasks[0].state, '完了');
assert.equal(sceneState('60件のタスク').tasks.length, 60); assert.equal(sceneState('タスクなし').tasks.length, 0); assert(!sceneState('入力待ちなし').tasks.some(t => t.state === '入力待ち'));
const rerun = sceneState('複数の報告').tasks.find(t => t.id === 'questions')!;
const anchor = 'questions-history-1-work', snapshot = structuredClone(rerun);
assert(successorCellIds(rerun, anchor).has('questions-r1-report'));
assert.equal(addCellInstruction(rerun, anchor, '別の対象で再確認'), false); assert.deepEqual(rerun, snapshot);
assert.equal(addCellInstruction(rerun, anchor, '別の対象で再確認', true), true);
assert.equal(rerun.flow.rounds.length, 1); assert.equal(rerun.flow.reports.length, 0); assert.equal(rerun.artifacts.length, 0);
const rerunCell = flowCells(rerun.flow).find(c => c.id === anchor)!;
assert.equal(rerunCell.state, '動作中'); assert.equal(rerunCell.output, ''); assert(rerunCell.attempts[0].input); assert(rerunCell.attempts[0].output); assert.deepEqual(rerunCell.extraInputs, ['別の対象で再確認']);
assert.equal(rerun.state, '進行中'); assert.equal(waitingSeconds(rerun), 0);
const parallelTask = seed().tasks.find(t => t.id === 'api')!, parallelIds = parallelTask.flow.rounds[0].branches[1].cells.map(c => c.id);
parallelTask.flow.rounds[0].branches[0].cells[0].state = '終わった';
assert(addCellInstruction(parallelTask, 'api-implement', 'ここだけ再実行', true)); assert(parallelIds.every(id => flowCells(parallelTask.flow).some(c => c.id === id)));
const liveInput = seed().tasks.find(t => t.id === 'api')!; assert(addCellInstruction(liveInput, 'api-implement', '動作中の追加')); assert.equal(liveInput.flow.rounds[0].branches[0].cells[0].extraInputs.length, 1);
const timeTask = seed().tasks[0]; timeTask.lastInstructionAt = 100000; timeTask.waitingSince = 160000; assert.equal(taskElapsedSeconds(timeTask, 280000), 60); assert.equal(waitingSeconds(timeTask, 280000), 120);
const metrics = [{ title: '任意の単位', value: '101%', limit: '100%' }, { title: '利用額', value: '1$', alert: 'critical' }]; assert.deepEqual(parseUsage(JSON.stringify(metrics)), metrics); assert.equal(parseUsage(JSON.stringify(metrics))[0].alert, undefined); assert.throws(() => parseUsage('{}'));
const legacy = seed(); legacy.version = 2; delete (legacy as Partial<typeof legacy>).skills; const upgraded = migrate(legacy); assert.equal(upgraded.version, 3); assert(upgraded.skills.length > 0);
const reportRerun = seed().tasks.find(t => t.id === 'result')!; assert(addCellInstruction(reportRerun, reportRerun.flow.reports[0].id, '説明を短く', true)); const reportState = seed(); reportState.tasks = [reportRerun]; advance(reportState, reportRerun.id); assert.equal(reportRerun.state, '入力待ち'); assert.equal(reportRerun.flow.reports.length, 1);
const files = (dir: string): string[] => readdirSync(dir, { withFileTypes: true }).flatMap(d => d.isDirectory() ? files(`${dir}/${d.name}`) : [`${dir}/${d.name}`]);
for (const path of files('src')) assert(!/\p{Extended_Pictographic}/u.test(readFileSync(path, 'utf8')), `Emoji in ${path}`);
const design = readFileSync('docs/ux-design.md', 'utf8'); for (let i = 1; i <= 12; i++) assert(design.includes(`UC${i} |`)); for (let i = 1; i <= 9; i++) assert(design.includes(`## ${i}.`));
writeFileSync('docs/model-verification.json', JSON.stringify({ tasks: s.tasks.length, executors: s.executors.length, largeFlow: { rounds: 8, cells: 30 }, reportCharacters: longReport.length, codexConcurrentCells: 3, emojiFilesChecked: files('src').length, simulationSteps: steps, passed: true }, null, 2) + '\n');
console.log(`見本・操作・段階進行の整合性を確認しました。長文報告 ${longReport.length} 字。`);
